global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'authservice'
    static_configs:
      - targets: ['authservice:8081']
    metrics_path: /metrics

  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:8080']
    metrics_path: /metrics

  - job_name: 'cartservice'
    static_configs:
      - targets: ['cartservice:7070']
    metrics_path: /metrics

  - job_name: 'checkoutservice'
    static_configs:      
      - targets: ['checkoutservice:5050']
    metrics_path: /metrics

  - job_name: 'productcatalogservice'
    static_configs:
      - targets: ['productcatalogservice:3550']
    metrics_path: /metrics

  - job_name: 'adservice'
    static_configs:
      - targets: ['adservice:9555']
    metrics_path: /metrics